kanta = int(input("Mikä on kanta?"))
korkeus = int(input("Mitä on korkeus?"))
piiri = 2 * (kanta + korkeus)
pinta_ala = (kanta * korkeus)
print("Suorakulmion piiri on: ", piiri)
print("Suorakulmion pinta_ala on:", pinta_ala)
